# Generated by Django 3.0.5 on 2020-05-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name="Author's name")),
                ('email', models.EmailField(max_length=100, verbose_name="Author's email")),
                ('profile_pic', models.ImageField(blank=True, default='prof_pic1.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=30, verbose_name='Ad title')),
                ('ad_text', models.CharField(max_length=60, verbose_name='Ad text')),
                ('ad_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Article name')),
                ('article_text', models.TextField(verbose_name='Article text')),
                ('pub_date', models.DateTimeField(verbose_name='Publication date')),
                ('type', models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('TECH', 'TECH'), ('SCIENCE', 'SCIENCE'), ('OTHER', 'OTHER')], max_length=30, verbose_name='Type of article')),
                ('article_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=60, verbose_name="Author's name")),
                ('author_organisation', models.CharField(max_length=80, verbose_name="Author's organisation")),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200, null=True, verbose_name='Comment text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Account')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Author'),
        ),
    ]
