# Generated by Django 3.0.5 on 2020-05-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Anonymous', max_length=60, verbose_name="Author's name"),
        ),
    ]
